# Generated by Django 4.2.7 on 2023-11-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('Introducao', models.TextField()),
                ('Desenvolvimento', models.TextField()),
                ('Conclusao', models.TextField()),
                ('img', models.ImageField(upload_to='Redacoes/%Y/%m/%d')),
            ],
        ),
    ]
