# Generated by Django 4.2.7 on 2023-11-18 20:59

import ProvaAntiga.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, upload_to=ProvaAntiga.models.pdf_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('files', models.ManyToManyField(to='ProvaAntiga.file', verbose_name='pdfs')),
            ],
        ),
    ]
