# Generated by Django 4.2.7 on 2023-11-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProvaAntiga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='pdf',
            field=models.FileField(blank=True, upload_to='Midia/%Y/%m/%d'),
        ),
    ]
