# Generated by Django 4.2.7 on 2023-11-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProvaAntiga', '0002_file_name_alter_file_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='ano',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
